v0.3.0 update
perun-network/perun-eth-mobile pull request #20
Opened 2020-06-04 17:44 UTC by ggwpez

2020-06-04 17:45 UTC, ggwpez commented on client.go
> +// Incoming proposals and updates are forwarded to the passed handlers.
Will add links

2020-06-10 13:38 UTC, ggwpez commented
Please focus the review on the bindings since we add the `Channel.Peers()` function and that will change the example. @sebastianst

2020-06-18 13:41 UTC, sebastianst requested changes
Example looks good. Please rename the Acceptor to a callback, as mentioned in the review comments.

2020-06-18 13:41 UTC, sebastianst commented on client.go
> +	}
The naming is very confusing. This is not an `Acceptor` but only a callback/event consumer. There's nothing to accept here, the channel already got accepted and created. Please change this to something like
```suggestion
	// NewChannelCallback wraps a `func(*PaymentChannel)`
	// function pointer for the `Client.OnNewChannel` callback.
	NewChannelCallback interface {
		OnNew(*PaymentChannel)
	}
```
Also change the naming everywhere.

2020-06-18 13:41 UTC, sebastianst commented on client.go
> +	c.acceptor = acc
Remove `c.acceptor` field from type `Client`. Always keep as few state as possible. It is only used here locally to set the `OnNewChannel` callback.

2020-06-18 13:41 UTC, sebastianst commented on client.go
> +		c.acceptor.Accept(&PaymentChannel{ch})
```suggestion
		callback.Accept(&PaymentChannel{ch})
```

2020-06-18 13:41 UTC, sebastianst commented on client.go
> +func (c *Client) OnNewChannel(acc ChannelAcceptor) {
```suggestion
func (c *Client) OnNewChannel(callback NewChannelCallback) {
```

2020-06-18 13:41 UTC, sebastianst commented on client.go
> +		acceptor ChannelAcceptor
Remove `c.acceptor` field from type `Client`. Always keep as few state as possible.
```suggestion
```

2020-06-22 13:59 UTC, ggwpez commented
I have to change the example to the new interface naming… We really need a pipeline :laughing:

2020-06-22 18:04 UTC, sebastianst approved these changes

2020-06-22 18:04 UTC, merged