V0.5.2 update
perun-network/perun-eth-mobile pull request #30
Opened 2020-11-03 13:56 UTC by ggwpez

2020-11-10 10:03 UTC, sebastianst requested changes

2020-11-10 10:03 UTC, sebastianst commented on channel.go
> +	return c.ch.Update(ctx.ctx, state)
Please boyscout-fix to use `UpdateBy`, then you can omit the cloning and version++

2020-11-10 10:03 UTC, sebastianst commented on channel.go
> +	return c.ch.Update(ctx.ctx, state)
Please boyscout-fix to use `UpdateBy`, then you can omit the cloning and version++

2020-11-10 10:03 UTC, sebastianst commented on client_proposal.go
> +	"errors"
we use `"github.com/pkg/errors"` in this project.

2020-11-10 10:03 UTC, sebastianst commented on client_proposal.go
> +		client.WithoutApp())
don't ignore the error here...

2020-11-10 10:03 UTC, sebastianst commented on client_proposal.go
> +		return nil
I'd remove the `default` case and just return after the switch

2020-11-10 10:03 UTC, sebastianst commented on client_proposal.go
> +	switch true {
doesn't just `switch {` work?

2020-11-10 10:03 UTC, sebastianst commented on client_proposal.go
> +		return errors.New("only two-party channels are supported")
I think those two checks are already done inside `validTwoPartyProposal` in the framework. Please check.

2020-11-10 10:03 UTC, sebastianst commented on client_proposal.go
> +		Participant       *Address // The peer proposing the channel.
This rename is misleading, because this is the peer/wire address not channel participant. I'd leave it as is or just call it `Peer`.

2020-11-10 10:03 UTC, sebastianst commented on client_proposal.go
> -	val, err := rand.Int(rand.Reader, limitUint256)
do you also delete the superfluous `limitUint256` variable?

2020-11-10 10:03 UTC, sebastianst commented on README.md
> +
We already mention at the top
> Right now it only provides two-party-payment channels.

I'd delete this Feature section and just change the above statement to
> Right now, it supports two-party single-asset ledger payment channels.

2020-11-10 10:03 UTC, sebastianst commented on android/app/src/main/java/network/perun/app/MainActivity.java
> +            Log.i("prnm", String.format("Channel proposal (id=%s, bals=[%d,%d])", proposal.getParticipant().toHex(), bals.get(0).toInt64(), bals.get(1).toInt64()));
Note, will change to `getPeer()`, it's not the participant.

2020-11-10 12:03 UTC, ggwpez commented on client_proposal.go
> +		client.WithoutApp())
Oh, we dont have a linter here :laughing: I will run it locally

2020-11-10 12:05 UTC, ggwpez commented on client_proposal.go
> +	switch true {
:thinking: did now knot that yet

2020-11-10 12:20 UTC, ggwpez commented on client_proposal.go
> +		return errors.New("only two-party channels are supported")
Correct, i removed the two check.

2020-11-10 12:33 UTC, ggwpez commented on client_proposal.go
> +		Participant       *Address // The peer proposing the channel.
Hm ok i renamed it since we call it the same in `LedgerChannelProposal`.

2020-11-10 12:34 UTC, ggwpez commented on client_proposal.go
> -	val, err := rand.Int(rand.Reader, limitUint256)
It seems the whole `nonce` function is not needed anyway right now :laughing:

2020-11-10 12:42 UTC, sebastianst commented on client_proposal.go
> -	val, err := rand.Int(rand.Reader, limitUint256)
Ah yes, we can now pass it as an option. Then please remove it.

2020-11-11 18:48 UTC, sebastianst approved these changes

2020-11-11 18:49 UTC, merged